@startuml
'https://plantuml.com/class-diagram

class Operation {
    double numberA
    double numberB
    double getResult()
}

class OperationAdd {
    double getResult()
}
class OperationSub {
    double getResult()
}
class OperationMul {
    double getResult()
}
class OperationDiv {
    double getResult()
}

class OperationFactory {
    {static} Operation createOperation()
}

Operation <|-- OperationAdd
Operation <|-- OperationSub
Operation <|-- OperationMul
Operation <|-- OperationDiv
OperationFactory ..> Operation

@enduml