@startuml
'https://plantuml.com/class-diagram

abstract Operation {
    double numberA
    double numberB
    {abstract} double getResult()
}
note left: Abstract Product

package "Concrete Product"{
class OperationAdd {
    double getResult()
}
class OperationSub {
    double getResult()
}
class OperationMul {
    double getResult()
}
class OperationDiv {
    double getResult()
}
}

interface IFactory {
    Operation createOperation()
}
note right: Abstract Factory

package "Concrete Factory"{
class AddFactory{
    Operation createOperation()
}
class SubFactory{
    Operation createOperation()
}
class DivFactory{
    Operation createOperation()
}
class MulFactory{
    Operation createOperation()
}
}

IFactory <|-- AddFactory
IFactory <|-- SubFactory
IFactory <|-- DivFactory
IFactory <|-- MulFactory

Operation <|-- OperationAdd
Operation <|-- OperationSub
Operation <|-- OperationMul
Operation <|-- OperationDiv
Operation <. IFactory

OperationAdd <.[#green] AddFactory
OperationSub <.[#green] SubFactory
OperationDiv <.[#green] DivFactory
OperationMul <.[#green] MulFactory

@enduml